#รับค่าข้อมูลทางแป้นพิมพ์ด้วย python เอาข้อมูลไปใช้ให้สร้างตัวแปร(variable) intครอบข้อมูลเลขจน.เต็ม strบวกลบคูณหารไม่ได้
name = input('ป้อนชื่อ : ')
yearBorn = input('ป้อนปีเกิด : ')
print('---------------------------')
#ฟังก์ชันในการแปลงข้อมูลขจากข้อความเป็นตัวเลข int(), float()
#ฟังก์ชันในการแปลงข้อมูลขจากตัวเลขเป็นข้อความ str()
print(f'ยินดีต้อนรับคุณ {name} เกิดปี {yearBorn} อายุ {2023 - int(yearBorn) }')
print('ยินดีต้อนรับคุณ',name,'เกิดปี',yearBorn,'อายุ',2023-int(yearBorn))
print('ยินดีต้อนรับคุณ '+name+' เกิดปี '+yearBorn+' อายุ '+ str(2023-int(yearBorn)))
print('ยินดีต้อนรับคุณ {} เกิดปี {} อายุ {}'.format(name,yearBorn,2023 - int(yearBorn)))
print('ยินดีต้อนรับคุณ %s เกิดปี %s อายุ %d' %(name,yearBorn,2023 - int(yearBorn)))